import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1f0a3f',
  },
  loadingText: {
    color: '#2dd4bf',
    marginTop: 16,
    fontSize: 14,
  },
  topNav: {
    backgroundColor: '#1f0a3f',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(45, 212, 191, 0.3)',
    paddingTop: 50,
    paddingBottom: 12,
  },
  navContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#2dd4bf',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  logoEmoji: {
    fontSize: 20,
  },
  logoText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f5f7fb',
  },
  loginButton: {
    backgroundColor: '#22c55e',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  loginButtonText: {
    color: '#f5f7fb',
    fontWeight: 'bold',
    fontSize: 14,
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroSection: {
    height: 400,
    position: 'relative',
    marginBottom: 20,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 0,
    pointerEvents: 'none',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 1,
    pointerEvents: 'box-none',
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#f5f7fb',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 40,
  },
  heroSubtitle: {
    fontSize: 16,
    color: '#e7e9ef',
    textAlign: 'center',
    marginBottom: 24,
  },
  ctaButton: {
    backgroundColor: '#22c55e',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  ctaButtonText: {
    color: '#f5f7fb',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: '#2a1557',
    marginHorizontal: 20,
    borderRadius: 16,
    marginBottom: 24,
  },
  statCard: {
    alignItems: 'center',
  },
  statIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2dd4bf',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#c7c9d3',
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#f5f7fb',
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#c7c9d3',
  },
  seeAllButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  seeAllText: {
    color: '#2dd4bf',
    fontWeight: 'bold',
    fontSize: 14,
  },
  classCard: {
    width: 280,
    backgroundColor: '#2a1557',
    borderRadius: 16,
    marginRight: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 251, 0.12)',
  },
  classCardEnrolled: {
    borderColor: '#22c55e',
    backgroundColor: 'rgba(34,197,94,0.08)',
  },
  cardHover: {
    transform: [{ translateY: -4 }],
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  classCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  classIcon: {
    fontSize: 32,
  },
  levelBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  levelText: {
    color: '#f5f7fb',
    fontSize: 11,
    fontWeight: 'bold',
  },
  classCardBody: {
    padding: 16,
  },
  className: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#f5f7fb',
    marginBottom: 6,
  },
  classProfessor: {
    fontSize: 14,
    color: '#d6d7df',
    marginBottom: 12,
  },
  classInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoIcon: {
    fontSize: 14,
    marginRight: 6,
  },
  infoText: {
    fontSize: 13,
    color: '#c7c9d3',
  },
  reserveButton: {
    backgroundColor: '#22c55e',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  reserveButtonText: {
    color: '#f5f7fb',
    fontWeight: 'bold',
    fontSize: 14,
  },
  sportCard: {
    width: 320,
    backgroundColor: '#2a1557',
    borderRadius: 16,
    marginRight: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 251, 0.12)',
  },
  sportImage: {
    width: '100%',
    height: 180,
  },
  sportOverlay: {
    position: 'absolute',
    top: 16,
    left: 16,
  },
  sportBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  sportBadgeText: {
    color: '#f5f7fb',
    fontWeight: 'bold',
    fontSize: 16,
  },
  sportContent: {
    padding: 16,
  },
  sportDescription: {
    fontSize: 14,
    color: '#d6d7df',
    marginBottom: 16,
    lineHeight: 20,
  },
  benefitsContainer: {
    marginBottom: 16,
  },
  benefitsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#f5f7fb',
    marginBottom: 8,
  },
  benefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  benefitDot: {
    color: '#2dd4bf',
    fontSize: 16,
    marginRight: 8,
  },
  benefitText: {
    fontSize: 13,
    color: '#c7c9d3',
  },
  exploreSportButton: {
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  exploreSportText: {
    color: '#f5f7fb',
    fontWeight: 'bold',
    fontSize: 14,
  },
  testimonialCard: {
    width: 300,
    backgroundColor: '#2a1557',
    borderRadius: 16,
    padding: 20,
    marginRight: 16,
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 251, 0.12)',
  },
  testimonialHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  testimonialImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#2dd4bf',
  },
  testimonialInfo: {
    flex: 1,
  },
  testimonialName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#f5f7fb',
    marginBottom: 2,
  },
  testimonialAge: {
    fontSize: 12,
    color: '#c7c9d3',
    marginBottom: 6,
  },
  ratingContainer: {
    flexDirection: 'row',
  },
  star: {
    fontSize: 12,
    marginRight: 2,
  },
  achievementBadge: {
    backgroundColor: 'rgba(45, 212, 191, 0.18)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  achievementText: {
    color: '#2dd4bf',
    fontSize: 12,
    fontWeight: 'bold',
  },
  testimonialText: {
    fontSize: 14,
    color: '#d6d7df',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  finalCTA: {
    backgroundColor: '#2a1557',
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 251, 0.12)',
  },
  finalCTATitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#f5f7fb',
    marginBottom: 12,
    textAlign: 'center',
  },
  finalCTASubtitle: {
    fontSize: 14,
    color: '#c7c9d3',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  finalCTAButton: {
    backgroundColor: '#22c55e',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  finalCTAButtonText: {
    color: '#f5f7fb',
    fontSize: 16,
    fontWeight: 'bold',
  },
  ratingRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  starRate: {
    fontSize: 24,
    marginRight: 8,
  },
  starActive: { color: '#f59e0b' },
  starInactive: { color: '#444' },
  feedbackInput: {
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.3)',
    borderRadius: 12,
    padding: 12,
    minHeight: 80,
    color: '#f5f7fb',
    marginBottom: 12,
    backgroundColor: 'rgba(45, 212, 191, 0.08)'
  },
  // estilos da navegação inferior removidos
});
